### Create a user
POST http://localhost:9090/social_media/users
content-type: application/json

{
    "birthDate": {
        "year": 1987,
        "month": 2,
        "day": 6
    },
    "name": "Rimas",
    "mobileNumbers": ["+94718923456"]
}

HTTP/1.1 201  - Created
content-length: 0
connection: close
server: ballerina
date: Wed, 7 May 2025 23:31:39 +0530
###
GET http://localhost:9090/social_media/users
###
GET http://localhost:9090/social_media/users/1
###
GET http://localhost:9090/social_media/users/3/posts
###
POST http://localhost:9090/social_media/users/3/posts
content-type: application/json

{
    "description": "I want to learn Azure",
    "tags": "azure,cloud,devops",
    "category": "education"
}
###
DELETE http://localhost:9090/social_media/users/1
###
POST http://localhost:9099/text-processing/api/sentiment

{
    "text": "I love this product"
}